### ISSUE TITLE
Armitage  Memory / Stalling / Unresponsive

### ISSUE THREAD

**Issue by ContactLeft** [ParrotSec/armitage#1]
Hello, 

The tool Armitage has issues when running on Parrot.  

It regularly runs out of memory  and lags when testing a large collection of hosts.  

This is noticed when running as stated above  and will become non responsive or even unusable.  

System used had >8Gb of Ram and an identical test was used running a similar pentesting environment given the same scenario.  

Tests conducted were numerous devices imported into the database with aux/shodan_gather in metasploit.

**Comment by PalinuroSec** [comment]
hello, this problem does not seem to be related to the armitage packaging in the parrot distro, but it seems to be related to the armitage internals and you should report your problem to the armitage developers (fastandeasyhacking.com), and not us (parrotsec.org) because we do not develop armitage, we have just packaged it for our distro


let me know if you need further help reporting the issue in the proper place
